import germanEmoji from "emojibase-data/de/compact.json";
import englishEmoji from "emojibase-data/en/compact.json";

export const expenseIconKeys = [
  "other",
  "housing",
  "groceries",
  "dining",
  "drinks",
  "transport",
  "fuel",
  "travel",
  "shopping",
  "entertainment",
  "health",
  "pharmacy",
  "education",
  "bills",
  "subscriptions",
  "gifts",
  "pets",
  "childcare",
  "sports",
  "personal-care",
  "work",
  "finance",
  "insurance",
  "taxes",
] as const;

export type ExpenseIconKey = (typeof expenseIconKeys)[number];

type ExpenseIconDefinition = {
  key: Exclude<ExpenseIconKey, "other">;
  emojiHexcodes: readonly string[];
  keywords: readonly string[];
  fragments?: readonly string[];
};

const expenseIconDefinitions: readonly ExpenseIconDefinition[] = [
  {
    key: "housing",
    emojiHexcodes: ["1F3E0", "1F3D8", "1F6CB", "1F6CF"],
    keywords: [
      "rent",
      "rental",
      "mortgage",
      "landlord",
      "tenant",
      "apartment",
      "flat",
      "house",
      "home",
      "housing",
      "furniture",
      "renovation",
      "repair",
      "miete",
      "kaltmiete",
      "warmmiete",
      "nebenkosten",
      "vermieter",
      "wohnung",
      "eigenheim",
      "haus",
      "möbel",
      "moebel",
      "renovierung",
      "reparatur",
      "ikea",
    ],
    fragments: ["miet", "wohn", "moebel", "möbel", "renovier"],
  },
  {
    key: "groceries",
    emojiHexcodes: [
      "1F35E",
      "1F95B",
      "1F955",
      "1F34E",
      "1F96C",
      "1F9C0",
      "1F95A",
    ],
    keywords: [
      "groceries",
      "grocery",
      "supermarket",
      "food shop",
      "market",
      "produce",
      "butcher",
      "bakery",
      "aldi",
      "lidl",
      "rewe",
      "edeka",
      "kaufland",
      "netto",
      "penny",
      "tegut",
      "real",
      "hit markt",
      "globus",
      "bio company",
      "denns",
      "whole foods",
      "walmart",
      "costco",
      "tesco",
      "sainsbury",
      "waitrose",
      "carrefour",
      "spar",
      "coop",
      "migros",
      "lebensmittel",
      "lebensmitteleinkauf",
      "supermarkt",
      "wochenmarkt",
      "markt",
      "metzger",
      "metzgerei",
      "bäcker",
      "baecker",
      "bäckerei",
      "baeckerei",
      "getränkemarkt",
      "getraenkemarkt",
    ],
    fragments: [
      "lebensmittel",
      "supermarkt",
      "wochenmarkt",
      "metzger",
      "baecker",
      "bäcker",
    ],
  },
  {
    key: "dining",
    emojiHexcodes: ["1F37D", "1F374", "1F35D", "1F355", "1F354"],
    keywords: [
      "restaurant",
      "dinner",
      "lunch",
      "breakfast",
      "brunch",
      "meal",
      "takeaway",
      "takeout",
      "delivery",
      "cafe",
      "coffee",
      "pizza",
      "burger",
      "sushi",
      "kebab",
      "mcdonalds",
      "burger king",
      "kfc",
      "subway",
      "starbucks",
      "dominos",
      "uber eats",
      "deliveroo",
      "wolt",
      "restaurant",
      "abendessen",
      "mittagessen",
      "frühstück",
      "fruehstueck",
      "brunch",
      "essen",
      "imbiss",
      "lieferdienst",
      "lieferando",
      "café",
      "kaffee",
      "pizzeria",
      "döner",
      "doener",
      "kantine",
      "mensa",
      "bistro",
    ],
    fragments: ["restaurant", "liefer", "pizzeria"],
  },
  {
    key: "drinks",
    emojiHexcodes: ["2615", "1F37A", "1F37B", "1F377", "1F379", "1F9CB"],
    keywords: [
      "drinks",
      "drink",
      "bar",
      "pub",
      "beer",
      "wine",
      "cocktail",
      "club",
      "nightclub",
      "brewery",
      "beverage",
      "getränke",
      "getraenke",
      "bar",
      "kneipe",
      "bier",
      "wein",
      "cocktail",
      "club",
      "nachtclub",
      "brauerei",
    ],
    fragments: ["getraenk", "getränk", "brauerei"],
  },
  {
    key: "transport",
    emojiHexcodes: [
      "1F68C",
      "1F686",
      "1F68B",
      "1F695",
      "1F697",
      "1F6B2",
      "1F6F4",
    ],
    keywords: [
      "car",
      "automobile",
      "vehicle",
      "taxi",
      "uber",
      "lyft",
      "bolt",
      "bus",
      "train",
      "tram",
      "subway",
      "metro",
      "rail",
      "railway",
      "ticket",
      "parking",
      "toll",
      "bike",
      "bicycle",
      "scooter",
      "public transport",
      "deutsche bahn",
      "bvg",
      "mvg",
      "hvv",
      "vbb",
      "vvs",
      "rmv",
      "kvb",
      "auto",
      "fahrzeug",
      "taxi",
      "bus",
      "bahn",
      "zug",
      "straßenbahn",
      "strassenbahn",
      "u-bahn",
      "s-bahn",
      "nahverkehr",
      "fahrkarte",
      "ticket",
      "parken",
      "parkhaus",
      "maut",
      "fahrrad",
      "roller",
    ],
    fragments: [
      "fahrkart",
      "parkgeb",
      "parkhaus",
      "strassenbahn",
      "straßenbahn",
      "nahverkehr",
    ],
  },
  {
    key: "fuel",
    emojiHexcodes: ["26FD"],
    keywords: [
      "fuel",
      "petrol",
      "gasoline",
      "gas station",
      "charging station",
      "electric charging",
      "shell",
      "esso",
      "bp",
      "chevron",
      "texaco",
      "aral",
      "total energies",
      "jet",
      "hem",
      "tankstelle",
      "tanken",
      "benzin",
      "diesel",
      "sprit",
      "ladestation",
      "ladesäule",
      "ladesaeule",
    ],
    fragments: ["tank", "benzin", "diesel", "ladestation", "ladesaul"],
  },
  {
    key: "travel",
    emojiHexcodes: ["2708", "1F3E8", "1F9F3", "1F6EB", "1F6EC"],
    keywords: [
      "flight",
      "airline",
      "airport",
      "airplane",
      "plane",
      "hotel",
      "hostel",
      "airbnb",
      "booking",
      "vacation",
      "holiday",
      "trip",
      "travel",
      "luggage",
      "resort",
      "cruise",
      "ferry",
      "ryanair",
      "easyjet",
      "lufthansa",
      "eurowings",
      "flug",
      "flugzeug",
      "flughafen",
      "airline",
      "hotel",
      "hostel",
      "ferienwohnung",
      "urlaub",
      "reise",
      "gepäck",
      "gepaeck",
      "kreuzfahrt",
      "fähre",
      "faehre",
    ],
    fragments: ["flug", "urlaub", "ferienwohnung", "kreuzfahrt"],
  },
  {
    key: "shopping",
    emojiHexcodes: ["1F6CD", "1F45A", "1F45F", "1F4BB", "1F4F1"],
    keywords: [
      "shopping",
      "shop",
      "store",
      "clothes",
      "clothing",
      "shoes",
      "fashion",
      "electronics",
      "computer",
      "phone",
      "amazon",
      "ebay",
      "etsy",
      "zalando",
      "asos",
      "h&m",
      "uniqlo",
      "primark",
      "mediamarkt",
      "saturn",
      "apple store",
      "einkaufen",
      "einkauf",
      "geschäft",
      "geschaeft",
      "laden",
      "kleidung",
      "schuhe",
      "mode",
      "elektronik",
      "computer",
      "handy",
    ],
    fragments: ["einkauf", "kleidung", "elektronik", "handy"],
  },
  {
    key: "entertainment",
    emojiHexcodes: ["1F3AC", "1F3A5", "1F3AE", "1F3AB", "1F3B5", "1F37F"],
    keywords: [
      "cinema",
      "movie",
      "film",
      "theater",
      "theatre",
      "concert",
      "festival",
      "museum",
      "exhibition",
      "game",
      "gaming",
      "playstation",
      "xbox",
      "nintendo",
      "steam",
      "event",
      "ticketmaster",
      "amusement park",
      "zoo",
      "kino",
      "film",
      "theater",
      "konzert",
      "festival",
      "museum",
      "ausstellung",
      "spiel",
      "gaming",
      "veranstaltung",
      "freizeitpark",
      "zoo",
    ],
    fragments: ["kino", "konzert", "festival", "ausstellung", "freizeitpark"],
  },
  {
    key: "health",
    emojiHexcodes: ["1F3E5", "1FA7A", "1F9B7", "1FA7B"],
    keywords: [
      "doctor",
      "dentist",
      "hospital",
      "clinic",
      "medical",
      "medicine",
      "therapy",
      "physiotherapy",
      "optician",
      "glasses",
      "emergency",
      "health",
      "arzt",
      "ärztin",
      "aerztin",
      "zahnarzt",
      "krankenhaus",
      "klinik",
      "medizin",
      "therapie",
      "physiotherapie",
      "optiker",
      "brille",
      "notaufnahme",
      "gesundheit",
    ],
    fragments: [
      "arzt",
      "ärzt",
      "aerzt",
      "zahn",
      "therap",
      "physio",
      "klin",
      "gesund",
    ],
  },
  {
    key: "pharmacy",
    emojiHexcodes: ["1F48A", "1F9F4", "1F9FC"],
    keywords: [
      "pharmacy",
      "chemist",
      "medication",
      "prescription",
      "medicine",
      "pills",
      "drugstore",
      "apotheke",
      "medikament",
      "rezept",
      "tabletten",
      "arzneimittel",
      "drogerie",
      "dm",
      "rossmann",
      "müller",
      "mueller",
    ],
    fragments: ["apothek", "medikament", "arznei", "drogerie"],
  },
  {
    key: "education",
    emojiHexcodes: ["1F3EB", "1F4DA", "1F393", "1F4D6", "1F392"],
    keywords: [
      "school",
      "university",
      "college",
      "tuition",
      "course",
      "class",
      "lesson",
      "training",
      "book",
      "textbook",
      "stationery",
      "udemy",
      "coursera",
      "schule",
      "universität",
      "universitaet",
      "hochschule",
      "studium",
      "studiengebühr",
      "studiengebuehr",
      "kurs",
      "unterricht",
      "weiterbildung",
      "buch",
      "bücher",
      "buecher",
      "lehrbuch",
      "schreibwaren",
    ],
    fragments: ["studien", "universit", "hochschul", "weiterbild", "unterricht"],
  },
  {
    key: "bills",
    emojiHexcodes: ["1F4A1", "1F6B0", "1F525", "1F4F1", "1F4E1"],
    keywords: [
      "electricity",
      "electric bill",
      "power bill",
      "water bill",
      "gas bill",
      "heating",
      "utility",
      "utilities",
      "internet",
      "broadband",
      "wifi",
      "phone bill",
      "mobile bill",
      "telephone",
      "telecom",
      "vodafone",
      "telekom",
      "o2",
      "1&1",
      "comcast",
      "verizon",
      "at&t",
      "strom",
      "stromrechnung",
      "wasser",
      "wasserrechnung",
      "gasrechnung",
      "heizung",
      "energie",
      "internet",
      "telefon",
      "handyrechnung",
      "nebenkosten",
      "rundfunkbeitrag",
      "gez",
    ],
    fragments: [
      "strom",
      "wasser",
      "heiz",
      "energie",
      "telefon",
      "handyrechnung",
      "rundfunk",
    ],
  },
  {
    key: "subscriptions",
    emojiHexcodes: ["1F501", "1F4FA", "1F3A7"],
    keywords: [
      "subscription",
      "membership",
      "monthly plan",
      "annual plan",
      "netflix",
      "spotify",
      "disney plus",
      "disney+",
      "amazon prime",
      "prime video",
      "youtube premium",
      "apple music",
      "icloud",
      "dropbox",
      "patreon",
      "audible",
      "adobe",
      "microsoft 365",
      "google one",
      "abo",
      "abonnement",
      "mitgliedschaft",
      "monatsbeitrag",
      "jahresbeitrag",
      "gez",
    ],
    fragments: ["abonn", "mitgliedschaft", "monatsbeitrag", "jahresbeitrag"],
  },
  {
    key: "gifts",
    emojiHexcodes: ["1F381", "1F382", "1F48C", "1F490"],
    keywords: [
      "gift",
      "present",
      "birthday",
      "wedding",
      "christmas",
      "donation",
      "charity",
      "flowers",
      "geschenk",
      "geburtstag",
      "hochzeit",
      "weihnachten",
      "spende",
      "wohltätigkeit",
      "wohltaetigkeit",
      "blumen",
    ],
    fragments: ["geschenk", "geburtstag", "hochzeit", "weihnacht", "spende"],
  },
  {
    key: "pets",
    emojiHexcodes: ["1F436", "1F431", "1F43E", "1F415", "1F408"],
    keywords: [
      "pet",
      "pets",
      "dog",
      "cat",
      "veterinarian",
      "vet",
      "pet food",
      "dog food",
      "cat food",
      "groomer",
      "tier",
      "haustier",
      "hund",
      "katze",
      "tierarzt",
      "tierärztin",
      "tieraerztin",
      "tierfutter",
      "hundefutter",
      "katzenfutter",
    ],
    fragments: ["haustier", "tierarzt", "tierfutter", "hundefutter", "katzenfutter"],
  },
  {
    key: "childcare",
    emojiHexcodes: ["1F476", "1F9F8", "1F37C"],
    keywords: [
      "childcare",
      "daycare",
      "nursery",
      "babysitter",
      "baby",
      "children",
      "kids",
      "diapers",
      "toys",
      "kindergarten",
      "kita",
      "krippe",
      "tagesmutter",
      "babysitter",
      "baby",
      "kinder",
      "windeln",
      "spielzeug",
    ],
    fragments: [
      "kita",
      "kinder",
      "kindergarten",
      "tagesmutter",
      "windel",
      "spielzeug",
    ],
  },
  {
    key: "sports",
    emojiHexcodes: ["26BD", "1F3C0", "1F3CB", "1F3CA", "1F3BE", "1F3BF"],
    keywords: [
      "sport",
      "sports",
      "gym",
      "gym membership",
      "fitness",
      "fitness membership",
      "football",
      "soccer",
      "basketball",
      "tennis",
      "swimming",
      "skiing",
      "yoga",
      "climbing",
      "running",
      "marathon",
      "peloton",
      "sport",
      "fitnessstudio",
      "fitnessmitgliedschaft",
      "fußball",
      "fussball",
      "basketball",
      "tennis",
      "schwimmen",
      "ski",
      "yoga",
      "klettern",
      "laufen",
    ],
    fragments: ["fitness", "fussball", "fußball", "schwimm", "kletter"],
  },
  {
    key: "personal-care",
    emojiHexcodes: ["1F487", "1F488", "1F485", "1F9F4", "1F9FC", "1F9F4"],
    keywords: [
      "haircut",
      "hairdresser",
      "barber",
      "salon",
      "beauty",
      "cosmetics",
      "makeup",
      "skincare",
      "spa",
      "massage",
      "nails",
      "friseur",
      "haarschnitt",
      "barbier",
      "salon",
      "kosmetik",
      "schminke",
      "hautpflege",
      "wellness",
      "massage",
      "nagelstudio",
    ],
    fragments: ["friseur", "haarschnitt", "kosmetik", "hautpfleg", "nagelstudio"],
  },
  {
    key: "work",
    emojiHexcodes: ["1F4BC", "1F6E0", "1F4BB", "1F5A8"],
    keywords: [
      "work",
      "office",
      "business",
      "coworking",
      "equipment",
      "software",
      "supplies",
      "conference",
      "client",
      "beruf",
      "arbeit",
      "büro",
      "buero",
      "geschäftlich",
      "geschaeftlich",
      "coworking",
      "ausrüstung",
      "ausruestung",
      "software",
      "büromaterial",
      "bueromaterial",
      "konferenz",
      "kunde",
    ],
    fragments: ["bueromaterial", "büromaterial", "geschaeft", "geschäft"],
  },
  {
    key: "finance",
    emojiHexcodes: ["1F3E6", "1F4B3", "1FA99", "1F4B0", "1F4B8"],
    keywords: [
      "bank",
      "bank fee",
      "bank charge",
      "interest",
      "loan",
      "credit",
      "credit card",
      "cash",
      "atm",
      "exchange fee",
      "paypal",
      "wise",
      "revolut",
      "broker",
      "investment",
      "bank",
      "bankgebühr",
      "bankgebuehr",
      "kontogebühr",
      "kontogebuehr",
      "zinsen",
      "kredit",
      "kreditkarte",
      "bargeld",
      "geldautomat",
      "wechselgebühr",
      "wechselgebuehr",
      "broker",
      "anlage",
    ],
    fragments: ["bankgeb", "kontogeb", "kredit", "geldautomat", "wechselgeb"],
  },
  {
    key: "insurance",
    emojiHexcodes: ["1F6E1", "1F510"],
    keywords: [
      "insurance",
      "insurer",
      "coverage",
      "liability insurance",
      "health insurance",
      "car insurance",
      "home insurance",
      "life insurance",
      "allianz",
      "axa",
      "huk",
      "ergo",
      "versicherung",
      "versicherer",
      "haftpflicht",
      "krankenversicherung",
      "kfz versicherung",
      "hausratversicherung",
      "lebensversicherung",
      "rechtsschutz",
    ],
    fragments: ["versicher", "haftpflicht", "rechtsschutz"],
  },
  {
    key: "taxes",
    emojiHexcodes: ["1F3DB", "1F4C4", "1F9FE"],
    keywords: [
      "tax",
      "taxes",
      "income tax",
      "property tax",
      "vat",
      "irs",
      "tax office",
      "accountant",
      "steuer",
      "steuern",
      "einkommensteuer",
      "lohnsteuer",
      "grundsteuer",
      "mehrwertsteuer",
      "umsatzsteuer",
      "finanzamt",
      "steuerberater",
    ],
    fragments: ["steuer", "finanzamt"],
  },
];

const ignoredEmojiTerms = new Set([
  "action",
  "animal",
  "ball",
  "body",
  "box",
  "building",
  "celebration",
  "country",
  "face",
  "food",
  "heart",
  "object",
  "people",
  "person",
  "place",
  "red",
  "simple",
  "symbol",
  "vehicle",
  "where",
]);

type EmojiRecord = {
  hexcode: string;
  label: string;
  tags?: string[];
};

function normalizeExpenseName(value: string) {
  return value
    .normalize("NFKD")
    .replace(/\p{M}/gu, "")
    .replace(/ß/g, "ss")
    .toLocaleLowerCase("en")
    .replace(/&/g, " and ")
    .replace(/[^\p{L}\p{N}+]+/gu, " ")
    .trim()
    .replace(/\s+/g, " ");
}

function localizedEmojiTerms(
  records: readonly EmojiRecord[],
  hexcodes: readonly string[],
) {
  const selected = new Set(hexcodes);
  return records
    .filter((record) => selected.has(record.hexcode))
    .flatMap((record) => [record.label, ...(record.tags ?? [])])
    .map(normalizeExpenseName)
    .filter(
      (term) =>
        term.length >= 3 &&
        !ignoredEmojiTerms.has(term) &&
        !/^\d+$/.test(term),
    );
}

type PreparedDefinition = {
  key: Exclude<ExpenseIconKey, "other">;
  keywords: readonly { term: string; boost: number }[];
  fragments: readonly string[];
};

const preparedDefinitions: readonly PreparedDefinition[] =
  expenseIconDefinitions.map((definition) => ({
    key: definition.key,
    keywords: [
      ...new Set(
        definition.keywords.map(normalizeExpenseName).filter(Boolean),
      ),
    ].map((term) => ({ term, boost: 200 })),
    emojiKeywords: [
      ...new Set([
        ...localizedEmojiTerms(englishEmoji, definition.emojiHexcodes),
        ...localizedEmojiTerms(germanEmoji, definition.emojiHexcodes),
      ]),
    ],
    fragments: [
      ...new Set((definition.fragments ?? []).map(normalizeExpenseName)),
    ],
  })).map(({ emojiKeywords, ...definition }) => ({
    ...definition,
    keywords: [
      ...definition.keywords,
      ...emojiKeywords
        .filter(
          (term) =>
            !definition.keywords.some((keyword) => keyword.term === term),
        )
        .map((term) => ({ term, boost: 0 })),
    ],
  }));

function keywordScore(normalizedName: string, keyword: string) {
  if (normalizedName === keyword) return 1_000 + keyword.length;
  if (` ${normalizedName} `.includes(` ${keyword} `)) {
    return 500 + keyword.split(" ").length * 20 + keyword.length;
  }
  return 0;
}

export function detectExpenseIconKey(name: string): ExpenseIconKey {
  const normalizedName = normalizeExpenseName(name);
  if (!normalizedName) return "other";
  const tokens = normalizedName.split(" ");
  let best: { key: ExpenseIconKey; score: number } = {
    key: "other",
    score: 0,
  };

  for (const definition of preparedDefinitions) {
    for (const keyword of definition.keywords) {
      const baseScore = keywordScore(normalizedName, keyword.term);
      const score = baseScore > 0 ? baseScore + keyword.boost : 0;
      if (score > best.score) best = { key: definition.key, score };
    }
    for (const fragment of definition.fragments) {
      if (
        fragment.length >= 4 &&
        tokens.some((token) => token.includes(fragment))
      ) {
        const score = 300 + fragment.length;
        if (score > best.score) best = { key: definition.key, score };
      }
    }
  }

  return best.key;
}

export function normalizeExpenseIconKey(
  value: unknown,
  expenseName = "",
): ExpenseIconKey {
  if (
    typeof value === "string" &&
    value !== "other" &&
    (expenseIconKeys as readonly string[]).includes(value)
  ) {
    return value as ExpenseIconKey;
  }
  return detectExpenseIconKey(expenseName);
}
